### ISSUE TITLE
coding requirements checklist

### ISSUE THREAD

**Issue by sherryzheng2018** [Project2-Team-5/Coder-Mingle#13]
- [x] must use a Node and Express web server;
- [x] must be backed by a MySQL database with a Sequelize ORM;
- [x] must have both GET and POST routes for retrieving and adding new data; (maybe also add DELETE and PULL functions?);
- [x] must be deployed using Heroku；
- [x] must utilize at least one new library, package, or tech that haven't discussed;
- [x] must have a front end/UI utilizing Handlebars;
- [x] must have a folder structure that meets the MVC paradigm;
- [x] must include authentication (sessions and cookies);
- [x] must protect API keys in Node with .env variables
